### ISSUE TITLE
Package installation fails

### ISSUE THREAD

**Issue by yiannis-had** [app-generator/vuejs-argon-design-system#3]
Here's the output when I run yarn:

https://pastebin.com/VuEEVpVq

**Comment by app-generator** [comment]
Hello @yiannis-had,
Thanks for using this starter. If you have the time, please add more information regarding your OS and environment.

**Comment by yiannis-had** [comment]
I'm using Windows 10 , node v12.16.2 and yarn 1.22.4

**Comment by app-generator** [comment]
We will double-check this. Your system is quite close to our testbeds.

**Comment by sandrews** [comment]
Has this been resolved?  I see the same issues

argon-design-system $ uname -a && node --version  && yarn --version 
Darwin triangulam.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
v14.2.0
1.22.4

**Comment by yiannis-had** [comment]
Well there's no new commit in 9 months so no it hasn't

**Comment by app-generator** [comment]
Hello guys, 
Sorry for this temporary inactivity. We are prototyping in other technologies for now (e.g. Firebase). Once the Firebase is stable, we will stabilize the React, Vue app that uses Nodejs and Firebase in the backend. 

In case we are not upset you much, please join our [Discord](https://discord.gg/fZC6hup) server.
Thanks :)
